obj-$(CONFIG_HYPERV2)		+= hv_vmbus2.o
obj-$(CONFIG_HYPERV_UTILS2)	+= hv_utils2.o

hv_vmbus2-y := vmbus_drv2.o \
		 hv2.o connection2.o channel2.o \
		 channel_mgmt2.o ring_buffer2.o
hv_utils2-y := hv_util2.o 
